name: searchack
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.14
  cupertino_icons: ^1.0.2
  drift: ^2.2.0
  firebase_auth: ^3.3.17
  firebase_core: ^1.16.0
  firebase_storage: ^10.2.15
  flutter:
    sdk: flutter
  html:
  image_picker: ^0.8.5+3
  multi_select_flutter: ^4.1.2
  path: ^1.8.2
  path_provider: ^2.0.0
  provider: ^6.0.2
  sqlite3_flutter_libs: ^0.5.0
  web_scraper: ^0.1.4
  webview_flutter: null

dev_dependencies:
  build_runner: ^2.2.1
  drift_dev: ^2.2.0+1
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: null
  network_image_mock: null

flutter:
  uses-material-design: true
  assets:
    - assets/
